VALUES
    personnal home: ecomerce go------------------------
    client : dashboard personnal
    entreprise et parametre: profile-settings admin-profile-1-2-3-settings
    produit et parametre: list-datatable-1, table-flex-advanced  okay il reste --lien vers le produit, supprimer, modifier
    stock et parametre: admin-project-3 okay
    trace d'activité: admin-profile-notification
    employer et parametre: hr dashboard okay
    vente : utility-invoice okay
    facture: utility-invoice, voir la vente
    statistique financier: dashboard-finance-1
    demo : lifestyle video
    billing : saas-billing
    welcom: admin-welcom - okay il reste les liens
    approuver: kaban- valider annulation (vente, stock), flux de vente, trace
    detail produit : admin-dashbord personnal-1- rapport de vente d'une periode - pourcentage(en vente, en nombre de vente, en stockage), nombre de vente

main sidebar:
    1 : personal home employer
    2 : statistique financier
    3 : produit et parametre
    4 : stock et parametre
    5 : vente
    6 : demo

utiliser bitcoin price chart bankink-3 dans statistique financier
les produits les plus vendus